services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
   

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=production

volumes:
  postgres_data:
